name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm ci

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
        npm ci

    - name: Build frontend
      working-directory: ./frontend/TV-SeriesDisplaye-master
      run: npm run build

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Deploy to cPanel
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
        CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
      run: |
        # Install the cPanel CLI tool
        npm install -g cpanel-node
        
        # Deploy the application
        cpanel-node deploy \
          --host $CPANEL_HOST \
          --username $CPANEL_USERNAME \
          --password $CPANEL_PASSWORD \
          --path /public_html/movie_app \
          --files frontend/TV-SeriesDisplaye-master/dist/* backend/dist/*
