name: Deploy React and Node.js Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Install dependencies (frontend)
        run: |
          cd frontend/TV-SeriesDisplaye-master
          npm ci

      - name: Build frontend
        run: |
          cd frontend/TV-SeriesDisplaye-master
          npm run build

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm ci

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.FTP_HOST }}
          SSH_USERNAME: ${{ secrets.FTP_USERNAME }}
          SSH_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Install SSH client
          apt-get update && apt-get install -y openssh-client

          # Deploy frontend
          scp -r ./frontend/TV-SeriesDisplaye-master/dist/* $SSH_USERNAME@$SSH_HOST:/var/www/my-app/frontend/
          # Deploy backend
          scp -r ./backend/dist/* $SSH_USERNAME@$SSH_HOST:/var/www/my-app/backend/

          # Connect to server and restart the application
          ssh $SSH_USERNAME@$SSH_HOST <<EOF
            # Navigate to the application directory
            cd /var/www/my-app

            # Restart the backend service
            pm2 restart backend

            # Restart the frontend service
            pm2 restart frontend
          EOF

          # Check the deployment status
          if [ $? -ne 0 ]; then
            echo "Deployment failed. Exiting with error."
            exit 1
          else
            echo "Deployment successful."
          fi
