name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install frontend dependencies
      working-directory: ./frontend/TV-SeriesDisplaye-master
      run: |
        npm install
        npm ci

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
        npm ci
    - name: Build frontend
      working-directory: ./frontend/TV-SeriesDisplaye-master
      run: |
        npm run build

    - name: Deploy to cPanel
      env:
         CPANEL_HOST: ${{ secrets.FTP_Server }}
         CPANEL_USERNAME: ${{ secrets.FTP_Username }}
         CPANEL_PASSWORD: ${{ secrets.ftp_password }}
      run: |
        # Install the cPanel CLI tool
          --host $CPANEL_HOST \
          --username $CPANEL_USERNAME \
          --password $CPANEL_PASSWORD \
          --path /public_html/ \
          --files frontend/TV-SeriesDisplaye-master/build/* backend/dist/*
        
        # Check the deployment status
        if [ $? -ne 0 ]; then
          echo "Deployment failed. Exiting with error."
          exit 1
        else
          echo "Deployment successful."
        fi
