name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install frontend dependencies
      working-directory: ./frontend/TV-SeriesDisplaye-master
      run: |
        npm install
        npm ci

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm install
        npm ci

    - name: Build frontend
      working-directory: ./frontend/TV-SeriesDisplaye-master
      run: npm run build

  

    - name: Deploy to server
      env:
        SSH_HOST: ${{ secrets.FTP_HOST }}
        SSH_USERNAME: ${{ secrets.FTP_Username }}
        SSH_PASSWORD: ${{ secrets.ftp_password }}
      run: |
        # Install SSH client
        sudo apt-get update
        sudo apt-get install -y openssh-client

        # Deploy the application
        ssh $SSH_USERNAME@$SSH_HOST "rm -rf /path/to/your/server/directory/*"
        scp -r frontend/TV-SeriesDisplaye-master/build/* $SSH_USERNAME@$SSH_HOST:/path/to/your/server/directory/frontend
        scp -r backend/dist/* $SSH_USERNAME@$SSH_HOST:/path/to/your/server/directory/backend
