name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      run: npm run test
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci
        
    - name: Build application
      run: npm run build
        
    - name: Deploy to cPanel
      env:
        CPANEL_HOST: ${{ secrets.FTP_server }}
        CPANEL_USERNAME: ${{ secrets.FTP_Username }}
        CPANEL_PASSWORD: ${{ secrets.ftp_password }}
      run: |
        # Install the cPanel CLI tool
        npm install -g cpanel-node
        
        # Deploy the application
        cpanel-node deploy \
          --host $CPANEL_HOST \
          --username $CPANEL_USERNAME \
          --password $CPANEL_PASSWORD \
          --path /public_html/movie_app \
          --files dist/*
